### ISSUE TITLE
Intended meaning of era:inCountry

### ISSUE THREAD

**Issue by kvistgaard** [julianrojas87/era-vocabulary#6]
Currently IRI: `http://era.europa.eu/ns#inCountry` is defined with the intended use

_Indicates the country in which the entity resides._

```era:inCountry a owl:ObjectProperty, rdf:Property ;
    rdfs:label "in country"@en ;
    rdfs:comment "Indicates the country in which the entity resides."@en ;
    rdfs:isDefinedBy era: ;
    rdfs:domain [ a owl:Class ;
                  owl:unionOf ( era:OperationalPoint era:VehicleType )
                ] ;
    rdfs:range skos:Concept ;
    dct:created "2020-09-01"^^xsd:date ;
    dct:modified "2020-09-01"^^xsd:date ;
    vs:term_status "stable" .
```

It has domain `owl:unionOf ( era:OperationalPoint era:VehicleType` . OP have location rather than residence. For VT the issue the intended use is ambiguous: "manufactured in", "spend most of it's lifecycle in", "has manufacturer with coutry of residence" etc.

Possible solutions: changing the comment, creating a sub-property, changing the domain (OP or Manufacturer).

**Comment by julianrojas87** [comment]
Addressed in #10.
