### ISSUE TITLE
The domain of era:inCountry is unnecessarily restrictive

### ISSUE THREAD

**Issue by kvistgaard** [julianrojas87/era-vocabulary#7]
Currently the domain of era:inCountry is the union of VT and OP.

However, the actual use [is broader](http://era.ilabt.imec.be/sparql?name=Compatible%20Tracks%20for%20TRAXX%20F140&infer=true&sameAs=false&query=%23%20Compatible%20Tracks%20for%20Vehicle%20TRAXX%20F140%20DESE%20Var%20E%20(RINF%20%26%20ERATV)%0APREFIX%20era%3A%20%3Chttp%3A%2F%2Fera.europa.eu%2Fns%23%3E%0APREFIX%20skos%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0APREFIX%20gn%3A%20%3Chttp%3A%2F%2Fwww.geonames.org%2Fontology%23%3E%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%0Aselect%20distinct%20%3Fs_class%20%0A%0A%7B%3Fs%20era%3AinCountry%20%3Fo%20.%0A%0A%20%20%20%20%20%20%20%20%3Fs%20a%20%3Fs_class%20.%7D). 

1 | era:OperationalPoint
2 | geosparql:Feature
3 | wgs:SpatialThing
4 | era:VehicleType

Apart from that to allow for a higher interoperability and re-use, the era ontology should "learn" but not be coupled with the current dataset.
Suggestion: remove domain declaration and for orientation list in the note the typical expected domain classes, based on the current data set.

**Comment by julianrojas87** [comment]
Fixed in #10
